{
  "extends": "stylelint-config-standard",
  "rules": {
    "indentation": 4,
    "color-hex-case": "upper",
    "color-hex-length": "long",
    "at-rule-empty-line-before": ["always", { "except": ["inside-block", "after-same-name"],
        "ignore": ["after-comment"], "ignoreAtRules": ["font-face", "mixin", "apply"]}],
    "selector-pseudo-element-colon-notation": "single",
    "declaration-block-trailing-semicolon": null,
    "declaration-empty-line-before": ["always", {"except": ["first-nested", "after-comment"],
        "ignore": ["after-declaration"]}],
    # disable checking this rule because it's violated too often in the Bootstrap theme we're using
    "no-descending-specificity": null,
    "value-keyword-case": null,
    "at-rule-no-unknown": [true, {"ignoreAtRules": ["include", "mixin", "for", "each", "extend", "tailwind", "apply", "variants", "screen"]}]
  }
}
